# Generated by Django 5.1.5 on 2025-02-04 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_alter_modelfood_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subcat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.subcategory'),
        ),
    ]
