# Generated by Django 5.1.5 on 2025-02-05 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_category_subcat_category_subcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfood',
            name='data_atualization',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='modelfood',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
